### ISSUE TITLE
Mummichog local will not run on python3.11

### ISSUE THREAD

**Issue by jmmitc06** [shuzhao-li/mummichog#13]
Fresh install of mummichog via pip on python3.11 will not run. 

Error message is 

`Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/homebrew/lib/python3.11/site-packages/mummichog/main.py", line 29, in <module>
    from .functional_analysis import *
  File "/opt/homebrew/lib/python3.11/site-packages/mummichog/functional_analysis.py", line 30, in <module>
    from .get_user_data import *
  File "/opt/homebrew/lib/python3.11/site-packages/mummichog/get_user_data.py", line 24, in <module>
    from .models import *
  File "/opt/homebrew/lib/python3.11/site-packages/mummichog/models.py", line 17, in <module>
    import networkx as nx
  File "/opt/homebrew/lib/python3.11/site-packages/networkx/__init__.py", line 84, in <module>
    import networkx.generators
  File "/opt/homebrew/lib/python3.11/site-packages/networkx/generators/__init__.py", line 5, in <module>
    from networkx.generators.classic import *
  File "/opt/homebrew/lib/python3.11/site-packages/networkx/generators/classic.py", line 21, in <module>
    from networkx.algorithms.bipartite.generators import complete_bipartite_graph
  File "/opt/homebrew/lib/python3.11/site-packages/networkx/algorithms/__init__.py", line 12, in <module>
    from networkx.algorithms.dag import *
  File "/opt/homebrew/lib/python3.11/site-packages/networkx/algorithms/dag.py", line 2, in <module>
    from fractions import gcd
ImportError: cannot import name 'gcd' from 'fractions' (/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/fractions.py)
`

The root cause of this issue is that gcd has been moved from fractions to the math library but the version of networkx that is being used is not aware of this because it is older. Using a newer networkx though gives other error messages because some functions have been deprecated in newer versions.

The quick workaround is to install an older version of python (or using the web server) but ultimately I think we need to update the  code to use a newer networkx.

**Comment by shuzhao-li** [comment]
Fixed by [Update to v2.7 to use networkx version 2+]
